transfer_smart/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/contact', to: 'static_pages#contact'
  get '/signup',   to: 'users#new'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'


  post '/create_transfer', to: 'transfers#create'
  get '/exchange_info', to: 'exchange_infos#new'

  resources :users
  resources :transfers
  resources :exchange_infos
  resources :personal_infos
  resources :recipient_infos
  get '/personal_info', to: 'personal_infos#new'
  get '/recipient_info', to: 'recipient_infos#new'
  get '/transfer_summary', to: 'transfers#edit'
  get '/my_transfers', to: 'transfers#index'
  post '/webhook_response', to: 'webhooks#receive'
  post '/webhook_response_2', to: 'webhooks#receive_2'

#match '/curl_example' => 'webhooks#receive', via: :get
end

#BackToBasics::Application.routes.draw do
  
 # match '/curl_example' => 'webhooks#curl_post_example', via: :post
#end

transfer_smart/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://github.com/vagosdim/TransferSmart">international fund transfering web application</a>
    by <a href="https://github.com/vagosdim/">Evangelos Dimoulis</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", help_path %></li>
    </ul>
  </nav>
</footer>

transfer_smart/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse", id= "mybar">
  <div class="container">
    <%= link_to "TransferSmart", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

<%#dropdown is boostrap feature!
go to application.js and include jquery and bootstrap.
Also need gem jquery-rails %>

transfer_smart/app/views/layouts/_progress_bar.html.erb
<div class="container">
      <ul class="progressbar">
        <li class="active">Step 1</li>
        <li>Step 2</li>
        <li>Step 3</li>
      </ul>
</div>

transfer_smart/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

transfer_smart/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <meta name="turbolinks-cache-control" content="no-preview">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'true' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, name: :psj , action: action_name, controller: controller_name %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |flash_key, message| %>
        <div class="alert alert-<%= flash_key %>"><%= message %></div>
      <% end %>
      <%= yield %>
      
      <%#= debug(params) if Rails.env.development? %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>