transfer_smart/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/contact', to: 'static_pages#contact'
  get '/signup',   to: 'users#new'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout',to: 'sessions#destroy'


  post '/create_transfer', to: 'transfers#create'
  get '/exchange_info', to: 'exchange_infos#new'

  resources :users
  resources :transfers
  resources :exchange_infos
  resources :personal_infos
  resources :recipient_infos
  get '/personal_info', to: 'personal_infos#new'
  get '/recipient_info', to: 'recipient_infos#new'
  get '/transfer_summary', to: 'transfers#edit'
  get '/my_transfers', to: 'transfers#index'
  post '/webhook_response', to: 'webhooks#receive'
  post '/webhook_response_2', to: 'webhooks#receive_2'

#match '/curl_example' => 'webhooks#receive', via: :get
end

#BackToBasics::Application.routes.draw do
  
 # match '/curl_example' => 'webhooks#curl_post_example', via: :post
#end

transfer_smart/app/models/transfer.rb
class Transfer < ApplicationRecord
  scope :initiated, -> {where(status: 'Initiated')}
	belongs_to :user
	has_one :exchange_info, :dependent => :destroy
	has_one :personal_info, :dependent => :destroy
	has_one :recipient_info, :dependent => :destroy


	def receipt
    exchange_info = ExchangeInfo.find(exchange_info_id)
    amount_sent = exchange_info.sending_amount
    recipient = RecipientInfo.find(recipient_info_id)
    Receipts::Receipt.new(
      id: id,
      subheading: "RECEIPT FOR TRANSFER #%{id}",
      product: "TransferSmart",
      company: {
        name: "TransferSmart, Inc.",
        address: "University of Ioannina\nFloor 1\nIoannina Greece",
        email: "transfersmart.developer@gmail.com",
        logo: Rails.root.join("app/assets/images/rails-logo.jpeg")
      },
      line_items: [
        ["Sender", "#{user.name} (#{user.email})"],
        ["Recipient",        "#{recipient.name}"],
        ["IBAN",         "#{recipient.iban}"],
        ["Amount",     "#{amount_sent} #{exchange_info.currency_from}"],
        ["Transfer Reference", "#{reference}"],
        ["Date",           created_at.to_s]
      ]
    )
  end

end

transfer_smart/app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
    require "securerandom"

	include SessionsHelper
	include WebhooksHelper
	#skip_before_action :verify_authenticity_token
	#before_action :logged_in_user, only: [:edit, :show]

	def index
		user = current_user
		@transfers = user.transfers.order(created_at: :desc)
	end

	def destroy
		@transfer = Transfer.find(params[:id])
		if (@transfer)
			@transfer.destroy
			session.delete(:transfer_id)
			redirect_to '/my_transfers'
		end

	end


	def edit
		@transfer = ""
		if(params[:id])
			@transfer = Transfer.find(params[:id])
		else
			@transfer = Transfer.find(session[:transfer_id])
		end
		if(!@transfer.reference)
			create_unique_reference(@transfer)
		end
		session.delete(:transfer_id)
		@transfer.status = "Pending"
		@transfer.save
		@exchange_info = ExchangeInfo.find(@transfer.exchange_info_id)
		@recipient = RecipientInfo.find(@transfer.recipient_info_id)
		@recipient_name = @recipient.name
		sender = PersonalInfo.find(@transfer.personal_info_id)
		@sender = sender.first_name + " " + sender.last_name

		@account = @exchange_info.currency_from[0, @exchange_info.currency_from.length - 1] +
		            "-01-" + get_local_transfersmart_account_no(@recipient.bank_code)
		@amount = @exchange_info.sending_amount.to_s+"\t"+@exchange_info.currency_from
		@description = @transfer.reference

	end


	def update
		@transfer = Transfer.find(params[:id])
		if @transfer.update_attributes(status: "Initiated")		
			redirect_to '/my_transfers'
			HardWorker.perform_async(@transfer.id)
		else
			render 'edit'
		end
	end

	def show
		@transfer = Transfer.find(params[:id])
		respond_to do |format|
			format.pdf { 
				send_data(@transfer.receipt.render, 
				filename: "transfer-#{@transfer.id}-receipt.pdf",
				type: "application/pdf", 
			    disposition: :inline)
		    }
		end

	end

	private

		def create_unique_reference(transfer)
		    ref = (SecureRandom.hex(8)).upcase
		    t = Transfer.find_by(reference: ref)
		    while t
		      ref = (SecureRandom.hex(8)).upcase
		      t = Transfer.find_by(reference: ref)
		    end
		    transfer.reference = ref
		end

		def get_transfersmart_account_no(bank_code)
			server = "https://10.0.3.COUNTRY:443/fineract-provider/api/v1/"
			url = "https://10.0.3.COUNTRY:443/fineract-provider/api/v1/clients?displayName=TransferSmart"
			if(bank_code == "MFBNUSNY")
				url.sub!("COUNTRY", "149")
				server.sub!("COUNTRY", "149")
			elsif(bank_code == "MFBNEUAA")
				url.sub!("COUNTRY", "233")
				server.sub!("COUNTRY", "233")
			end
			transfer_smart_client = get_transfer_smart_client(url)
			transfer_smart_account = get_transfer_smart_savings_account(server+"clients/"+
 			                                  transfer_smart_client["id"].to_s+
 			                                  "/accounts")

 			return transfer_smart_account["accountNo"].to_s
		end


		def get_local_transfersmart_account_no(bank_code)
			server = "https://10.0.3.COUNTRY:443/fineract-provider/api/v1/"
			url = "https://10.0.3.COUNTRY:443/fineract-provider/api/v1/clients?displayName=TransferSmart"
			if(bank_code == "MFBNUSNY")
				url.sub!("COUNTRY", "233")
				server.sub!("COUNTRY", "233")
			elsif(bank_code == "MFBNEUAA")
				url.sub!("COUNTRY", "149")
				server.sub!("COUNTRY", "149")
			end
			transfer_smart_client = get_transfer_smart_client(url)
			transfer_smart_account = get_transfer_smart_savings_account(server+"clients/"+
 			                                  transfer_smart_client["id"].to_s+
 			                                  "/accounts")

 			return transfer_smart_account["accountNo"].to_s
		end



		def logged_in_user
      		unless logged_in?
        	store_location
        	flash[:danger] = "Require login to edit."
        	redirect_to login_url
      end
    end
end

transfer_smart/app/helpers/transfers_helper.rb
module TransfersHelper
	require 'net/http'
	require 'uri'
	require 'openssl'
	require 'json'

	include SessionsHelper
	

	def get_transfer_smart_client(url)
		transfer_smart_clients = get_request(url)
		transfer_smart_clients = JSON.parse(transfer_smart_clients.body)
		page_results = transfer_smart_clients["pageItems"]
		transfer_smart_client = ""
		page_results.select {|client|
 			if client["displayName"] == "TransferSmart"
   				transfer_smart_client = client 
 			end
 		}

 		return transfer_smart_client
	end

	def get_transfer_smart_savings_account(url)
		transfer_smart_accounts = get_request(url)
 		transfer_smart_accounts = JSON.parse(transfer_smart_accounts.body)
		transfer_smart_savings_account = transfer_smart_accounts["savingsAccounts"].first

		return transfer_smart_savings_account
	end


	def transfer_funds_to_recipient(transfer, target_server, client, accountId, description, recipient_email)
		account_type = 2
		todays_transfer_date = Date.today.strftime("%d")+" "+Date.today.strftime("%B")+" "+Date.today.strftime("%Y")
		exchange = ExchangeInfo.find(transfer.exchange_info_id)
		amount = exchange.receiving_amount.to_s
		transfer_smart_client = get_transfer_smart_client(target_server+"clients?displayName=TransferSmart&pretty=true") 

		transfer_smart_savings_account = get_transfer_smart_savings_account(target_server+"clients/"+
 			                                  transfer_smart_client["id"].to_s+
 			                                  "/accounts")
			

		uri = URI.parse(target_server+"accounttransfers")

		request = Net::HTTP::Post.new(uri)
		request.content_type = "application/json"
		request["Fineract-Platform-Tenantid"] = "default"
		request["Authorization"] = "Basic bWlmb3M6cGFzc3dvcmQ="
		request.body = JSON.dump({
		  "fromOfficeId" => transfer_smart_client["officeId"].to_i,
		  "fromClientId" => transfer_smart_client["id"].to_i,
		  "fromAccountType" => account_type,
		  "fromAccountId" => transfer_smart_savings_account["id"].to_i,
		  "toOfficeId" => client["officeId"].to_i,
		  "toClientId" => client["id"].to_i,
		  "toAccountType" => account_type,
		  "toAccountId" => accountId.to_i,
		  "dateFormat" => "dd MMMM yyyy",
		  "locale" => "en",
		  "transferDate" => todays_transfer_date,
		  "transferAmount" => amount,
		  "transferDescription" => description + "\t TransferSmart, Inc"
		})

		req_options = {
		  use_ssl: uri.scheme == "https",
		  verify_mode: OpenSSL::SSL::VERIFY_NONE,
		}

		response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
		  http.request(request)
		end
		if (response.kind_of? Net::HTTPSuccess)
			transfer.status = "Completed"
			transfer.save
			webhook = Webhook.find_by(reference: transfer.reference)
			Webhook.delete(webhook)
		end
		#ReceiptWorker.perform_async(transfer.id, sender_email, recipient_email)
	end
end

transfer_smart/app/views/transfers/_progress_bar.html.erb
<div class="container">
      <ul class="progressbar">
        <li class="active" id="step1">Step 1</li>
        <li id="step2">Step 2</li>
        <li id="step3">Step 3</li>
        <li id="step4">Step 4</li>
      </ul>
</div>

transfer_smart/app/views/transfers/_transfer.html.erb
<% if transfer.status == "Pending" %>
<%= link_to edit_transfer_path(transfer.id), class: "list-group-item" do%>
  <% if transfer.exchange_info_id %>
  	<%= ExchangeInfo.find(transfer.exchange_info_id).sending_amount%>
  	&nbsp;
  	<%= ExchangeInfo.find(transfer.exchange_info_id).currency_from%>
  	<div class=floatright>
  		to &nbsp;&nbsp;
  		<%= RecipientInfo.find(transfer.recipient_info_id).name  %>	
  	</div> 	
  <% end %> 
 <% end %>
<% end %>

transfer_smart/app/views/transfers/edit.html.erb
<% provide(:title, "Transfer Review") %>
<%= render '/transfers/progress_bar' %>

<div class="container" id="mypanel">
  <h3>Transfer Review</h3>
  
<div class="row">
	<div class="col-lg-6">
	  <div class="panel panel-default">
	    <div class="panel-heading">
	    	Instructions:
	    </div>
	    <ul class="list-group">
	      <li class="list-group-item">1. Login to your internet bank.</li>
		  <li class="list-group-item">2. Make a transfer from a bank account to 
		  	<b>TransferSmart</b>
		  	 using details on the right.</li>
		  <li class="list-group-item">3. <b><%=@recipient_name%></b> receives <%=@exchange_info.currency_to  %>.</li>
	    </ul>
	  </div>
	  	<%= form_for(@transfer) do |f|  %>
	  	 <%= f.submit "I HAVE SENT THE MONEY", class: "btn btn-primary" %>
	  	<% end  %>
	  	
	    <center>or</center> 
	    <center><%= link_to " Transfer the money later ", current_user  %></center>
    </div>

	<div class="col-lg-6">
	  <div class="panel panel-default">
	    <div class="panel-heading">
	    	Make the following transfer:
	    </div>
	    <ul class="list-group">
	      <li class="list-group-item">
	      	SENDER 
	      	<div class=floatright> <%= @sender %> </div>
	      </li>

		  <li class="list-group-item">
		  AMOUNT
		  <div class=floatright> <%= @amount %> </div>
		  </li>

		  <li class="list-group-item">
		  	TO
			<div class=floatright> TransferSmart </div>		  
		  </li>

		  <li class="list-group-item">
		  	ACCOUNT-TYPE
		  <div class=floatright> Savings-Account </div>		  
	      	
		  </li>
		  
		  <li class="list-group-item">
		  	ACCOUNT
		  	<div class=floatright> <%= @account  %> </div>		  
		  </li>

		  <li class="list-group-item">
		  	DESCRIPTION
		  	<div id="Reference" class=floatright> <%=@description  %> </div>	
		  		  
		  </li>

		  <li class="list-group-item">
		  OFFICE	
	      <div class=floatright> TransferSmartOffice </div>		  
		  </li>
	    </ul>
	  </div>
	  <center>
	  	Any problems? If any step is not clear enough <%= link_to " click here", "https://mifosforge.jira.com/wiki/spaces/docs/pages/73465980/How+to+Transfer+funds+from+a+Saving+Account"  %>
	  </center>
    </div>

</div>
  
</div>

transfer_smart/app/views/transfers/index.html.erb
<div class= "container-fluid">
      <table class="table">
        <h1>Transfer History</h1>
        <thead>
          <tr>
            <th>Recipient</th>
            <th>Amount</th>
            <th>Currency</th>
            <th>Status</th>
            <th>Created</th>
     
          </tr>
        </thead>
        <tbody>
          <% @transfers.each do |t| %>
            <tr>
              <% if RecipientInfo.find_by(id: t.recipient_info_id) %>
                <td><%= RecipientInfo.find(t.recipient_info_id).name  %></td>
              <% else %>
                <td> (None)</td>
              <% end %>

              <% if ExchangeInfo.find_by(id: t.exchange_info_id)  %>
                <% e = ExchangeInfo.find(t.exchange_info_id)%>
                <td> 
                    <%= e.sending_amount%>
                </td>
                <td>
                 &nbsp; <%= e.currency_from%>
                </td>
              <% else %>
                <td> </td><td> </td>
              <% end %>

              <td><%= t.status %></td>
              <td><%= t.created_at %></td>
              <% if t.status == "Completed" || t.status == "Initiated" %>  
                <td> <%= link_to 'Receipt', transfer_path(t, :pdf)  %></td>
              <% else %>
                <td>
                 <%= link_to 'Cancel', transfer_path(t.id), data: {:confirm => 'Are you sure?'}, :method => :delete %>
                   or
                  <%= link_to 'Review', edit_transfer_path(t.id) %>
                 </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
  </table>
    </div>